/*
* generated by Xtext
*/
package com.parallels.aps.ide.rqleditor.xtext.rql.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class RQLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperandsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOperandsHoOperandParserRuleCall_0_0 = (RuleCall)cOperandsAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_1_0 = (Alternatives)cGroup_1.eContents().get(0);
		private final Keyword cCommaKeyword_1_0_0 = (Keyword)cAlternatives_1_0.eContents().get(0);
		private final Keyword cAmpersandKeyword_1_0_1 = (Keyword)cAlternatives_1_0.eContents().get(1);
		private final RuleCall cHoOperandParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//Model:
		//	operands+=HoOperand (("," | "&") HoOperand)*;
		public ParserRule getRule() { return rule; }

		//operands+=HoOperand (("," | "&") HoOperand)*
		public Group getGroup() { return cGroup; }

		//operands+=HoOperand
		public Assignment getOperandsAssignment_0() { return cOperandsAssignment_0; }

		//HoOperand
		public RuleCall getOperandsHoOperandParserRuleCall_0_0() { return cOperandsHoOperandParserRuleCall_0_0; }

		//(("," | "&") HoOperand)*
		public Group getGroup_1() { return cGroup_1; }

		//"," | "&"
		public Alternatives getAlternatives_1_0() { return cAlternatives_1_0; }

		//","
		public Keyword getCommaKeyword_1_0_0() { return cCommaKeyword_1_0_0; }

		//"&"
		public Keyword getAmpersandKeyword_1_0_1() { return cAmpersandKeyword_1_0_1; }

		//HoOperand
		public RuleCall getHoOperandParserRuleCall_1_1() { return cHoOperandParserRuleCall_1_1; }
	}

	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAmpersandKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cHoOperandParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//And:
		//	"&" HoOperand;
		public ParserRule getRule() { return rule; }

		//"&" HoOperand
		public Group getGroup() { return cGroup; }

		//"&"
		public Keyword getAmpersandKeyword_0() { return cAmpersandKeyword_0; }

		//HoOperand
		public RuleCall getHoOperandParserRuleCall_1() { return cHoOperandParserRuleCall_1; }
	}

	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cSemicolonKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cVerticalLineKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final RuleCall cHoOperandParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Or:
		//	(";" | "|") HoOperand;
		public ParserRule getRule() { return rule; }

		//(";" | "|") HoOperand
		public Group getGroup() { return cGroup; }

		//";" | "|"
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//";"
		public Keyword getSemicolonKeyword_0_0() { return cSemicolonKeyword_0_0; }

		//"|"
		public Keyword getVerticalLineKeyword_0_1() { return cVerticalLineKeyword_0_1; }

		//HoOperand
		public RuleCall getHoOperandParserRuleCall_1() { return cHoOperandParserRuleCall_1; }
	}

	public class HoOperandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "HoOperand");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWSPTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cHigherOrderCallParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cCallOperatorParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cPredicateParserRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		private final RuleCall cComparisonParserRuleCall_1_3 = (RuleCall)cAlternatives_1.eContents().get(3);
		private final Group cGroup_1_4 = (Group)cAlternatives_1.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final RuleCall cHoOperandParserRuleCall_1_4_1 = (RuleCall)cGroup_1_4.eContents().get(1);
		private final Alternatives cAlternatives_1_4_2 = (Alternatives)cGroup_1_4.eContents().get(2);
		private final RuleCall cAndParserRuleCall_1_4_2_0 = (RuleCall)cAlternatives_1_4_2.eContents().get(0);
		private final RuleCall cOrParserRuleCall_1_4_2_1 = (RuleCall)cAlternatives_1_4_2.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_4_3 = (Keyword)cGroup_1_4.eContents().get(3);
		private final RuleCall cWSPTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//HoOperand:
		//	WSP* (HigherOrderCall | CallOperator | Predicate | Comparison | "(" HoOperand (And+ | Or+) ")") WSP*;
		public ParserRule getRule() { return rule; }

		//WSP* (HigherOrderCall | CallOperator | Predicate | Comparison | "(" HoOperand (And+ | Or+) ")") WSP*
		public Group getGroup() { return cGroup; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_0() { return cWSPTerminalRuleCall_0; }

		//HigherOrderCall | CallOperator | Predicate | Comparison | "(" HoOperand (And+ | Or+) ")"
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//HigherOrderCall
		public RuleCall getHigherOrderCallParserRuleCall_1_0() { return cHigherOrderCallParserRuleCall_1_0; }

		//CallOperator
		public RuleCall getCallOperatorParserRuleCall_1_1() { return cCallOperatorParserRuleCall_1_1; }

		//Predicate
		public RuleCall getPredicateParserRuleCall_1_2() { return cPredicateParserRuleCall_1_2; }

		//Comparison
		public RuleCall getComparisonParserRuleCall_1_3() { return cComparisonParserRuleCall_1_3; }

		//"(" HoOperand (And+ | Or+) ")"
		public Group getGroup_1_4() { return cGroup_1_4; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_4_0() { return cLeftParenthesisKeyword_1_4_0; }

		//HoOperand
		public RuleCall getHoOperandParserRuleCall_1_4_1() { return cHoOperandParserRuleCall_1_4_1; }

		//And+ | Or+
		public Alternatives getAlternatives_1_4_2() { return cAlternatives_1_4_2; }

		//And+
		public RuleCall getAndParserRuleCall_1_4_2_0() { return cAndParserRuleCall_1_4_2_0; }

		//Or+
		public RuleCall getOrParserRuleCall_1_4_2_1() { return cOrParserRuleCall_1_4_2_1; }

		//")"
		public Keyword getRightParenthesisKeyword_1_4_3() { return cRightParenthesisKeyword_1_4_3; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_2() { return cWSPTerminalRuleCall_2; }
	}

	public class HigherOrderCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "HigherOrderCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLOGICAL_OP_ALIASESTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cWSPTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cHoOperandParserRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final RuleCall cHoOperandParserRuleCall_3_1_1 = (RuleCall)cGroup_3_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//HigherOrderCall:
		//	LOGICAL_OP_ALIASES WSP* "(" (HoOperand ("," HoOperand)*) ")";
		public ParserRule getRule() { return rule; }

		//LOGICAL_OP_ALIASES WSP* "(" (HoOperand ("," HoOperand)*) ")"
		public Group getGroup() { return cGroup; }

		//LOGICAL_OP_ALIASES
		public RuleCall getLOGICAL_OP_ALIASESTerminalRuleCall_0() { return cLOGICAL_OP_ALIASESTerminalRuleCall_0; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_1() { return cWSPTerminalRuleCall_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//HoOperand ("," HoOperand)*
		public Group getGroup_3() { return cGroup_3; }

		//HoOperand
		public RuleCall getHoOperandParserRuleCall_3_0() { return cHoOperandParserRuleCall_3_0; }

		//("," HoOperand)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//HoOperand
		public RuleCall getHoOperandParserRuleCall_3_1_1() { return cHoOperandParserRuleCall_3_1_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class BinaryOpAliasesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BinaryOpAliases");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNeKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cEqKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cLtKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cLeKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cGtKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cGeKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cLikeKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		
		//BinaryOpAliases:
		//	"ne" | "eq" | "lt" | "le" | "gt" | "ge" | "like";
		public ParserRule getRule() { return rule; }

		//"ne" | "eq" | "lt" | "le" | "gt" | "ge" | "like"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"ne"
		public Keyword getNeKeyword_0() { return cNeKeyword_0; }

		//"eq"
		public Keyword getEqKeyword_1() { return cEqKeyword_1; }

		//"lt"
		public Keyword getLtKeyword_2() { return cLtKeyword_2; }

		//"le"
		public Keyword getLeKeyword_3() { return cLeKeyword_3; }

		//"gt"
		public Keyword getGtKeyword_4() { return cGtKeyword_4; }

		//"ge"
		public Keyword getGeKeyword_5() { return cGeKeyword_5; }

		//"like"
		public Keyword getLikeKeyword_6() { return cLikeKeyword_6; }
	}

	public class CompOpsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CompOps");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cExclamationMarkEqualsSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cLessThanSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cLessThanSignEqualsSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cGreaterThanSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cGreaterThanSignEqualsSignKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//CompOps:
		//	"!=" | "=" | "<" | "<=" | ">" | ">=";
		public ParserRule getRule() { return rule; }

		//"!=" | "=" | "<" | "<=" | ">" | ">="
		public Alternatives getAlternatives() { return cAlternatives; }

		//"!="
		public Keyword getExclamationMarkEqualsSignKeyword_0() { return cExclamationMarkEqualsSignKeyword_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//"<"
		public Keyword getLessThanSignKeyword_2() { return cLessThanSignKeyword_2; }

		//"<="
		public Keyword getLessThanSignEqualsSignKeyword_3() { return cLessThanSignEqualsSignKeyword_3; }

		//">"
		public Keyword getGreaterThanSignKeyword_4() { return cGreaterThanSignKeyword_4; }

		//">="
		public Keyword getGreaterThanSignEqualsSignKeyword_5() { return cGreaterThanSignEqualsSignKeyword_5; }
	}

	public class ComparisonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Comparison");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cStrvalParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cWSPTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final RuleCall cBinaryOpAliasesParserRuleCall_2_0_1 = (RuleCall)cGroup_2_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final RuleCall cCompOpsParserRuleCall_2_1 = (RuleCall)cAlternatives_2.eContents().get(1);
		private final RuleCall cPrimaryExprParserRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//Comparison:
		//	Strval WSP* ("=" BinaryOpAliases "=" | CompOps) PrimaryExpr;
		public ParserRule getRule() { return rule; }

		//Strval WSP* ("=" BinaryOpAliases "=" | CompOps) PrimaryExpr
		public Group getGroup() { return cGroup; }

		//Strval
		public RuleCall getStrvalParserRuleCall_0() { return cStrvalParserRuleCall_0; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_1() { return cWSPTerminalRuleCall_1; }

		//"=" BinaryOpAliases "=" | CompOps
		public Alternatives getAlternatives_2() { return cAlternatives_2; }

		//"=" BinaryOpAliases "="
		public Group getGroup_2_0() { return cGroup_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_2_0_0() { return cEqualsSignKeyword_2_0_0; }

		//BinaryOpAliases
		public RuleCall getBinaryOpAliasesParserRuleCall_2_0_1() { return cBinaryOpAliasesParserRuleCall_2_0_1; }

		//"="
		public Keyword getEqualsSignKeyword_2_0_2() { return cEqualsSignKeyword_2_0_2; }

		//CompOps
		public RuleCall getCompOpsParserRuleCall_2_1() { return cCompOpsParserRuleCall_2_1; }

		//PrimaryExpr
		public RuleCall getPrimaryExprParserRuleCall_3() { return cPrimaryExprParserRuleCall_3; }
	}

	public class CallOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CallOperator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final RuleCall cBinaryOpAliasesParserRuleCall_0_0 = (RuleCall)cAlternatives_0.eContents().get(0);
		private final RuleCall cFunctionsTblParserRuleCall_0_1 = (RuleCall)cAlternatives_0.eContents().get(1);
		private final RuleCall cWSPTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cPrimaryExprParserRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final RuleCall cPrimaryExprParserRuleCall_3_1_1 = (RuleCall)cGroup_3_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//CallOperator:
		//	(BinaryOpAliases | FunctionsTbl) WSP* "(" (PrimaryExpr ("," PrimaryExpr)*)? ")";
		public ParserRule getRule() { return rule; }

		//(BinaryOpAliases | FunctionsTbl) WSP* "(" (PrimaryExpr ("," PrimaryExpr)*)? ")"
		public Group getGroup() { return cGroup; }

		//BinaryOpAliases | FunctionsTbl
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//BinaryOpAliases
		public RuleCall getBinaryOpAliasesParserRuleCall_0_0() { return cBinaryOpAliasesParserRuleCall_0_0; }

		//FunctionsTbl
		public RuleCall getFunctionsTblParserRuleCall_0_1() { return cFunctionsTblParserRuleCall_0_1; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_1() { return cWSPTerminalRuleCall_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//(PrimaryExpr ("," PrimaryExpr)*)?
		public Group getGroup_3() { return cGroup_3; }

		//PrimaryExpr
		public RuleCall getPrimaryExprParserRuleCall_3_0() { return cPrimaryExprParserRuleCall_3_0; }

		//("," PrimaryExpr)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//PrimaryExpr
		public RuleCall getPrimaryExprParserRuleCall_3_1_1() { return cPrimaryExprParserRuleCall_3_1_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class PredicateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Predicate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPredTblParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final RuleCall cWSPTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cPrimaryExprParserRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cGroup_3.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final RuleCall cPrimaryExprParserRuleCall_3_1_1 = (RuleCall)cGroup_3_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Predicate:
		//	PredTbl WSP* "(" (PrimaryExpr ("," PrimaryExpr)*)? ")";
		public ParserRule getRule() { return rule; }

		//PredTbl WSP* "(" (PrimaryExpr ("," PrimaryExpr)*)? ")"
		public Group getGroup() { return cGroup; }

		//PredTbl
		public RuleCall getPredTblParserRuleCall_0() { return cPredTblParserRuleCall_0; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_1() { return cWSPTerminalRuleCall_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }

		//(PrimaryExpr ("," PrimaryExpr)*)?
		public Group getGroup_3() { return cGroup_3; }

		//PrimaryExpr
		public RuleCall getPrimaryExprParserRuleCall_3_0() { return cPrimaryExprParserRuleCall_3_0; }

		//("," PrimaryExpr)*
		public Group getGroup_3_1() { return cGroup_3_1; }

		//","
		public Keyword getCommaKeyword_3_1_0() { return cCommaKeyword_3_1_0; }

		//PrimaryExpr
		public RuleCall getPrimaryExprParserRuleCall_3_1_1() { return cPrimaryExprParserRuleCall_3_1_1; }

		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}

	public class PredTblElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PredTbl");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cSelectKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cSortKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cLimitKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cImplementingKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cComposingKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//PredTbl:
		//	"select" | "sort" | "limit" | "implementing" | "composing";
		public ParserRule getRule() { return rule; }

		//"select" | "sort" | "limit" | "implementing" | "composing"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"select"
		public Keyword getSelectKeyword_0() { return cSelectKeyword_0; }

		//"sort"
		public Keyword getSortKeyword_1() { return cSortKeyword_1; }

		//"limit"
		public Keyword getLimitKeyword_2() { return cLimitKeyword_2; }

		//"implementing"
		public Keyword getImplementingKeyword_3() { return cImplementingKeyword_3; }

		//"composing"
		public Keyword getComposingKeyword_4() { return cComposingKeyword_4; }
	}

	public class PrimaryExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimaryExpr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWSPTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final RuleCall cConstFuncTblParserRuleCall_1_0_0 = (RuleCall)cGroup_1_0.eContents().get(0);
		private final RuleCall cWSPTerminalRuleCall_1_0_1 = (RuleCall)cGroup_1_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0_2 = (Keyword)cGroup_1_0.eContents().get(2);
		private final RuleCall cWSPTerminalRuleCall_1_0_3 = (RuleCall)cGroup_1_0.eContents().get(3);
		private final Keyword cRightParenthesisKeyword_1_0_4 = (Keyword)cGroup_1_0.eContents().get(4);
		private final RuleCall cArrayParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		private final RuleCall cStrvalParserRuleCall_1_2 = (RuleCall)cAlternatives_1.eContents().get(2);
		private final RuleCall cWSPTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//PrimaryExpr:
		//	WSP* (ConstFuncTbl WSP* "(" WSP* ")" | Array | Strval) => WSP*;
		public ParserRule getRule() { return rule; }

		//WSP* (ConstFuncTbl WSP* "(" WSP* ")" | Array | Strval) => WSP*
		public Group getGroup() { return cGroup; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_0() { return cWSPTerminalRuleCall_0; }

		//ConstFuncTbl WSP* "(" WSP* ")" | Array | Strval
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//ConstFuncTbl WSP* "(" WSP* ")"
		public Group getGroup_1_0() { return cGroup_1_0; }

		//ConstFuncTbl
		public RuleCall getConstFuncTblParserRuleCall_1_0_0() { return cConstFuncTblParserRuleCall_1_0_0; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_1_0_1() { return cWSPTerminalRuleCall_1_0_1; }

		//"("
		public Keyword getLeftParenthesisKeyword_1_0_2() { return cLeftParenthesisKeyword_1_0_2; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_1_0_3() { return cWSPTerminalRuleCall_1_0_3; }

		//")"
		public Keyword getRightParenthesisKeyword_1_0_4() { return cRightParenthesisKeyword_1_0_4; }

		//Array
		public RuleCall getArrayParserRuleCall_1_1() { return cArrayParserRuleCall_1_1; }

		//Strval
		public RuleCall getStrvalParserRuleCall_1_2() { return cStrvalParserRuleCall_1_2; }

		//=> WSP*
		public RuleCall getWSPTerminalRuleCall_2() { return cWSPTerminalRuleCall_2; }
	}

	public class FunctionsTblElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FunctionsTbl");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cIsnullKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cInKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cOutKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//FunctionsTbl:
		//	"isnull" | "in" | "out";
		public ParserRule getRule() { return rule; }

		//"isnull" | "in" | "out"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"isnull"
		public Keyword getIsnullKeyword_0() { return cIsnullKeyword_0; }

		//"in"
		public Keyword getInKeyword_1() { return cInKeyword_1; }

		//"out"
		public Keyword getOutKeyword_2() { return cOutKeyword_2; }
	}

	public class ConstFuncTblElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConstFuncTbl");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cEmptyKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cNullKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		//ConstFuncTbl:
		//	"true" | "false" | "empty" | "null";
		public ParserRule getRule() { return rule; }

		//"true" | "false" | "empty" | "null"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }

		//"empty"
		public Keyword getEmptyKeyword_2() { return cEmptyKeyword_2; }

		//"null"
		public Keyword getNullKeyword_3() { return cNullKeyword_3; }
	}

	public class ArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Array");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cWSPTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cStrvalParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final RuleCall cWSPTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final RuleCall cWSPTerminalRuleCall_4_1 = (RuleCall)cGroup_4.eContents().get(1);
		private final RuleCall cStrvalParserRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		private final RuleCall cWSPTerminalRuleCall_4_3 = (RuleCall)cGroup_4.eContents().get(3);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Array:
		//	"(" WSP* Strval WSP* ("," WSP* Strval WSP*)* ")";
		public ParserRule getRule() { return rule; }

		//"(" WSP* Strval WSP* ("," WSP* Strval WSP*)* ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_1() { return cWSPTerminalRuleCall_1; }

		//Strval
		public RuleCall getStrvalParserRuleCall_2() { return cStrvalParserRuleCall_2; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_3() { return cWSPTerminalRuleCall_3; }

		//("," WSP* Strval WSP*)*
		public Group getGroup_4() { return cGroup_4; }

		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_4_1() { return cWSPTerminalRuleCall_4_1; }

		//Strval
		public RuleCall getStrvalParserRuleCall_4_2() { return cStrvalParserRuleCall_4_2; }

		//WSP*
		public RuleCall getWSPTerminalRuleCall_4_3() { return cWSPTerminalRuleCall_4_3; }

		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}

	public class NcharElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Nchar");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cALPHATerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDIGITTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword c_Keyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cTildeKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cDollarSignKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cAlternatives.eContents().get(7);
		private final Keyword cAsteriskKeyword_8 = (Keyword)cAlternatives.eContents().get(8);
		private final Keyword cPlusSignKeyword_9 = (Keyword)cAlternatives.eContents().get(9);
		private final Keyword cQuestionMarkKeyword_10 = (Keyword)cAlternatives.eContents().get(10);
		private final Keyword cSolidusKeyword_11 = (Keyword)cAlternatives.eContents().get(11);
		private final Keyword cCommercialAtKeyword_12 = (Keyword)cAlternatives.eContents().get(12);
		
		//Nchar:
		//	ALPHA | DIGIT | "-" | "." | "_" | "~" | "$" | ":" | "*" | "+" | "?" | "/" | "@";
		public ParserRule getRule() { return rule; }

		//ALPHA | DIGIT | "-" | "." | "_" | "~" | "$" | ":" | "*" | "+" | "?" | "/" | "@"
		public Alternatives getAlternatives() { return cAlternatives; }

		//ALPHA
		public RuleCall getALPHATerminalRuleCall_0() { return cALPHATerminalRuleCall_0; }

		//DIGIT
		public RuleCall getDIGITTerminalRuleCall_1() { return cDIGITTerminalRuleCall_1; }

		//"-"
		public Keyword getHyphenMinusKeyword_2() { return cHyphenMinusKeyword_2; }

		//"."
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }

		//"_"
		public Keyword get_Keyword_4() { return c_Keyword_4; }

		//"~"
		public Keyword getTildeKeyword_5() { return cTildeKeyword_5; }

		//"$"
		public Keyword getDollarSignKeyword_6() { return cDollarSignKeyword_6; }

		//":"
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }

		//"*"
		public Keyword getAsteriskKeyword_8() { return cAsteriskKeyword_8; }

		//"+"
		public Keyword getPlusSignKeyword_9() { return cPlusSignKeyword_9; }

		//"?"
		public Keyword getQuestionMarkKeyword_10() { return cQuestionMarkKeyword_10; }

		//"/"
		public Keyword getSolidusKeyword_11() { return cSolidusKeyword_11; }

		//"@"
		public Keyword getCommercialAtKeyword_12() { return cCommercialAtKeyword_12; }
	}

	public class Pct_encodedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Pct_encoded");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPercentSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cXDIGITTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cXDIGITTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Pct_encoded:
		//	"%" XDIGIT XDIGIT;
		public ParserRule getRule() { return rule; }

		//"%" XDIGIT XDIGIT
		public Group getGroup() { return cGroup; }

		//"%"
		public Keyword getPercentSignKeyword_0() { return cPercentSignKeyword_0; }

		//XDIGIT
		public RuleCall getXDIGITTerminalRuleCall_1() { return cXDIGITTerminalRuleCall_1; }

		//XDIGIT
		public RuleCall getXDIGITTerminalRuleCall_2() { return cXDIGITTerminalRuleCall_2; }
	}

	public class StrvalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Strval");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNcharParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPct_encodedParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Strval:
		//	(Nchar | Pct_encoded)+;
		public ParserRule getRule() { return rule; }

		//(Nchar | Pct_encoded)+
		public Alternatives getAlternatives() { return cAlternatives; }

		//Nchar
		public RuleCall getNcharParserRuleCall_0() { return cNcharParserRuleCall_0; }

		//Pct_encoded
		public RuleCall getPct_encodedParserRuleCall_1() { return cPct_encodedParserRuleCall_1; }
	}
	
	
	private ModelElements pModel;
	private AndElements pAnd;
	private OrElements pOr;
	private HoOperandElements pHoOperand;
	private HigherOrderCallElements pHigherOrderCall;
	private BinaryOpAliasesElements pBinaryOpAliases;
	private CompOpsElements pCompOps;
	private ComparisonElements pComparison;
	private CallOperatorElements pCallOperator;
	private PredicateElements pPredicate;
	private PredTblElements pPredTbl;
	private PrimaryExprElements pPrimaryExpr;
	private FunctionsTblElements pFunctionsTbl;
	private ConstFuncTblElements pConstFuncTbl;
	private ArrayElements pArray;
	private NcharElements pNchar;
	private Pct_encodedElements pPct_encoded;
	private StrvalElements pStrval;
	private TerminalRule tALPHA;
	private TerminalRule tDIGIT;
	private TerminalRule tXDIGIT;
	private TerminalRule tWSP;
	private TerminalRule tLOGICAL_OP_ALIASES;
	
	private final Grammar grammar;

	@Inject
	public RQLGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.parallels.aps.ide.rqleditor.xtext.rql.RQL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//Model:
	//	operands+=HoOperand (("," | "&") HoOperand)*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//And:
	//	"&" HoOperand;
	public AndElements getAndAccess() {
		return (pAnd != null) ? pAnd : (pAnd = new AndElements());
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}

	//Or:
	//	(";" | "|") HoOperand;
	public OrElements getOrAccess() {
		return (pOr != null) ? pOr : (pOr = new OrElements());
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}

	//HoOperand:
	//	WSP* (HigherOrderCall | CallOperator | Predicate | Comparison | "(" HoOperand (And+ | Or+) ")") WSP*;
	public HoOperandElements getHoOperandAccess() {
		return (pHoOperand != null) ? pHoOperand : (pHoOperand = new HoOperandElements());
	}
	
	public ParserRule getHoOperandRule() {
		return getHoOperandAccess().getRule();
	}

	//HigherOrderCall:
	//	LOGICAL_OP_ALIASES WSP* "(" (HoOperand ("," HoOperand)*) ")";
	public HigherOrderCallElements getHigherOrderCallAccess() {
		return (pHigherOrderCall != null) ? pHigherOrderCall : (pHigherOrderCall = new HigherOrderCallElements());
	}
	
	public ParserRule getHigherOrderCallRule() {
		return getHigherOrderCallAccess().getRule();
	}

	//BinaryOpAliases:
	//	"ne" | "eq" | "lt" | "le" | "gt" | "ge" | "like";
	public BinaryOpAliasesElements getBinaryOpAliasesAccess() {
		return (pBinaryOpAliases != null) ? pBinaryOpAliases : (pBinaryOpAliases = new BinaryOpAliasesElements());
	}
	
	public ParserRule getBinaryOpAliasesRule() {
		return getBinaryOpAliasesAccess().getRule();
	}

	//CompOps:
	//	"!=" | "=" | "<" | "<=" | ">" | ">=";
	public CompOpsElements getCompOpsAccess() {
		return (pCompOps != null) ? pCompOps : (pCompOps = new CompOpsElements());
	}
	
	public ParserRule getCompOpsRule() {
		return getCompOpsAccess().getRule();
	}

	//Comparison:
	//	Strval WSP* ("=" BinaryOpAliases "=" | CompOps) PrimaryExpr;
	public ComparisonElements getComparisonAccess() {
		return (pComparison != null) ? pComparison : (pComparison = new ComparisonElements());
	}
	
	public ParserRule getComparisonRule() {
		return getComparisonAccess().getRule();
	}

	//CallOperator:
	//	(BinaryOpAliases | FunctionsTbl) WSP* "(" (PrimaryExpr ("," PrimaryExpr)*)? ")";
	public CallOperatorElements getCallOperatorAccess() {
		return (pCallOperator != null) ? pCallOperator : (pCallOperator = new CallOperatorElements());
	}
	
	public ParserRule getCallOperatorRule() {
		return getCallOperatorAccess().getRule();
	}

	//Predicate:
	//	PredTbl WSP* "(" (PrimaryExpr ("," PrimaryExpr)*)? ")";
	public PredicateElements getPredicateAccess() {
		return (pPredicate != null) ? pPredicate : (pPredicate = new PredicateElements());
	}
	
	public ParserRule getPredicateRule() {
		return getPredicateAccess().getRule();
	}

	//PredTbl:
	//	"select" | "sort" | "limit" | "implementing" | "composing";
	public PredTblElements getPredTblAccess() {
		return (pPredTbl != null) ? pPredTbl : (pPredTbl = new PredTblElements());
	}
	
	public ParserRule getPredTblRule() {
		return getPredTblAccess().getRule();
	}

	//PrimaryExpr:
	//	WSP* (ConstFuncTbl WSP* "(" WSP* ")" | Array | Strval) => WSP*;
	public PrimaryExprElements getPrimaryExprAccess() {
		return (pPrimaryExpr != null) ? pPrimaryExpr : (pPrimaryExpr = new PrimaryExprElements());
	}
	
	public ParserRule getPrimaryExprRule() {
		return getPrimaryExprAccess().getRule();
	}

	//FunctionsTbl:
	//	"isnull" | "in" | "out";
	public FunctionsTblElements getFunctionsTblAccess() {
		return (pFunctionsTbl != null) ? pFunctionsTbl : (pFunctionsTbl = new FunctionsTblElements());
	}
	
	public ParserRule getFunctionsTblRule() {
		return getFunctionsTblAccess().getRule();
	}

	//ConstFuncTbl:
	//	"true" | "false" | "empty" | "null";
	public ConstFuncTblElements getConstFuncTblAccess() {
		return (pConstFuncTbl != null) ? pConstFuncTbl : (pConstFuncTbl = new ConstFuncTblElements());
	}
	
	public ParserRule getConstFuncTblRule() {
		return getConstFuncTblAccess().getRule();
	}

	//Array:
	//	"(" WSP* Strval WSP* ("," WSP* Strval WSP*)* ")";
	public ArrayElements getArrayAccess() {
		return (pArray != null) ? pArray : (pArray = new ArrayElements());
	}
	
	public ParserRule getArrayRule() {
		return getArrayAccess().getRule();
	}

	//Nchar:
	//	ALPHA | DIGIT | "-" | "." | "_" | "~" | "$" | ":" | "*" | "+" | "?" | "/" | "@";
	public NcharElements getNcharAccess() {
		return (pNchar != null) ? pNchar : (pNchar = new NcharElements());
	}
	
	public ParserRule getNcharRule() {
		return getNcharAccess().getRule();
	}

	//Pct_encoded:
	//	"%" XDIGIT XDIGIT;
	public Pct_encodedElements getPct_encodedAccess() {
		return (pPct_encoded != null) ? pPct_encoded : (pPct_encoded = new Pct_encodedElements());
	}
	
	public ParserRule getPct_encodedRule() {
		return getPct_encodedAccess().getRule();
	}

	//Strval:
	//	(Nchar | Pct_encoded)+;
	public StrvalElements getStrvalAccess() {
		return (pStrval != null) ? pStrval : (pStrval = new StrvalElements());
	}
	
	public ParserRule getStrvalRule() {
		return getStrvalAccess().getRule();
	}

	//terminal ALPHA:
	//	"A".."Z" | "a".."z";
	public TerminalRule getALPHARule() {
		return (tALPHA != null) ? tALPHA : (tALPHA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ALPHA"));
	} 

	//terminal DIGIT:
	//	"0".."9";
	public TerminalRule getDIGITRule() {
		return (tDIGIT != null) ? tDIGIT : (tDIGIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DIGIT"));
	} 

	//terminal XDIGIT:
	//	DIGIT | "A".."F";
	public TerminalRule getXDIGITRule() {
		return (tXDIGIT != null) ? tXDIGIT : (tXDIGIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "XDIGIT"));
	} 

	//terminal WSP:
	//	" " | "\t";
	public TerminalRule getWSPRule() {
		return (tWSP != null) ? tWSP : (tWSP = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WSP"));
	} 

	//terminal LOGICAL_OP_ALIASES:
	//	"or" | "and" | "not";
	public TerminalRule getLOGICAL_OP_ALIASESRule() {
		return (tLOGICAL_OP_ALIASES != null) ? tLOGICAL_OP_ALIASES : (tLOGICAL_OP_ALIASES = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LOGICAL_OP_ALIASES"));
	} 
}
