/*
* generated by Xtext
*/
package com.parallels.aps.ide.rqleditor.xtext.rql;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RQLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.parallels.aps.ide.rqleditor.xtext.rql.ui.internal.RQLActivator.getInstance().getInjector("com.parallels.aps.ide.rqleditor.xtext.rql.RQL");
	}
	
}
