/*
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RQLUiModule extends com.parallels.aps.ide.rqleditor.xtext.rql.ui.AbstractRQLUiModule {
	public RQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	// contributed by org.eclipse.xtext.generator.parser.antlr.ex.rt.AntlrGeneratorFragment
		public void configureHighlightingLexer(com.google.inject.Binder binder) {
			binder.bind(org.eclipse.xtext.parser.antlr.Lexer.class).
			annotatedWith(com.google.inject.name.Names.named
					(org.eclipse.xtext.ui.LexerUIBindings.HIGHLIGHTING)).
					to(com.parallels.aps.ide.rqleditor.xtext.rql.lexer.CustomRQLLexer.class);
		}
		
		public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
	        return SemanticHighlightingCalculator.class;
	}
}
