/**
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql.ui.contentassist;

import com.parallels.aps.ide.rqleditor.xtext.rql.ui.contentassist.AbstractRQLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class RQLProposalProvider extends AbstractRQLProposalProvider {
}
