/**
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class RQLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
