/**
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class RQLLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public RQLLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
