/*
* generated by Xtext
*/
package com.parallels.aps.ide.rqleditor.xtext.rql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RQLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/parallels/aps/ide/rqleditor/xtext/rql/parser/antlr/internal/InternalRQLParser.tokens");
	}
}
