/*
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRQLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.parallels.aps.ide.rqleditor.xtext.rql.rQL.RQLPackage.eINSTANCE);
		return result;
	}
}
