/**
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class RQLQuickfixProvider extends DefaultQuickfixProvider {
}
