/**
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql.validation;

import com.parallels.aps.ide.rqleditor.xtext.rql.validation.AbstractRQLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RQLValidator extends AbstractRQLValidator {
}
