/*
 * generated by Xtext
 */
package com.parallels.aps.ide.rqleditor.xtext.rql;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RQLRuntimeModule extends com.parallels.aps.ide.rqleditor.xtext.rql.AbstractRQLRuntimeModule {

}
